services:
  - type: web
    name: ficore-labs
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      python optimize_for_render.py
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PERFORMANCE_CACHE_TIMEOUT
        value: 3600
      - key: PERFORMANCE_STATIC_CACHE_TIMEOUT
        value: 2592000
      - key: PERFORMANCE_ENABLE_GZIP
        value: true
      - key: PERFORMANCE_ENABLE_ETAG
        value: true
      - key: MONGO_MAX_POOL_SIZE
        value: 50
      - key: MONGO_MIN_POOL_SIZE
        value: 5
    plan: starter