name: ficore_mobile
description: Ficore Africa Personal Finance Mobile App - Budget, Bills & Shopping (BBS)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage & Security
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Internationalization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # Date & Time
  table_calendar: ^3.0.9
  
  # Utilities
  uuid: ^4.2.1
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  
  # Form Validation
  form_validator: ^2.1.1
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Permissions
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700